### ISSUE TITLE
角色签到失败

### ISSUE THREAD

**Issue by LovesAsuna** [Tsuk1ko/genshin-mys-checkin#1]
TypeError: Cannot read property 'list' of null

我觉得我的secret填对了

**Comment by Tsuk1ko** [comment]
我觉得你填的 cookie 有问题，角色列表拿不到

需要注意你最好应当通过 F12 Network 去拿，而不是 `document.cookie`，后者会有缺失

**Comment by LovesAsuna** [comment]
就是通过network获取的

**Comment by Tsuk1ko** [comment]
你尝试退出登录，再登录一次，把 cookie 更新一下

**Comment by LovesAsuna** [comment]
确实更新一下cookie就能用了，也许是旧的cookie还不适配他新的算法.不过这个randomsleep是不是有点多余

**Comment by Tsuk1ko** [comment]
估计是，我加个错误提示吧

（随机一下多防一点总是好的，我看看能不能判断触发方式，手动的话就不 sleep 了
