### ISSUE TITLE
关于WebHook的问题

### ISSUE THREAD

**Issue by xANoyU** [Tsuk1ko/genshin-mys-checkin#3]
Webhook 调用失败 TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

我不懂wbconfig.json中的Webhook该如何填写..

**Comment by Tsuk1ko** [comment]
URL 中的参数如果含有中文或某些特殊符号，需要进行 URL 转义

**Comment by xANoyU** [comment]
> URL 中的参数如果含有中文或某些特殊符号，需要进行 URL 转义

如果要使用Server推送的话 webhook是不是直接在里面填写
https://sctapi.ftqq.com/****************.send?title=messagetitle&desp={{code}}  呢?

[
  {
    "alc": "xxxx"
    "webhook": "https://sctapi.ftqq.com/****************.send?title=messagetitle&desp={{code}}"
    "proxy": ""
  }
]

**Comment by Tsuk1ko** [comment]
是的

**Comment by xANoyU** [comment]
> 是的

感谢回答 问题解决了
