### ISSUE TITLE
微博超话签到失败问题

### ISSUE THREAD

**Issue by ShineJstar** [Tsuk1ko/genshin-mys-checkin#5]
你好，我拉代码在本机电脑docker跑的，微博签到时出现以下错误：
WB[0]
登录中
登录成功
保存 cookie 至缓存
Error: 签到失败: {"code":"100001","msg":"timezone is not allowed"}
暂无可领取礼包

我直接用只带cookie的请求头cURL请求能够签到成功，看代码也没找出问题，这是啥问题呢？

**Comment by Tsuk1ko** [comment]
curl 使用的 cookie 是你浏览器里的还是从项目 cache 里拿的

**Comment by ShineJstar** [comment]
> curl 使用的 cookie 是从项目 cache 里拿的么

不是，从浏览器里面拿的

**Comment by Tsuk1ko** [comment]
如果你使用 cache 中的 cookie 登录可能可以复现，不过得你自己找对应域名的自己拼 cookie 字符串

怀疑是登录拿到的 cookie 有什么问题，但这玩意应该跟时区没有关系才对，没有跟时区有关的参数，我在 GitHub Actions 里跑的也没发生过这类问题……
