### ISSUE TITLE
DS中的salt值是哪里来的

### ISSUE THREAD

**Issue by sunyajie0829** [Tsuk1ko/genshin-mys-checkin#6]
请问DS中的salt值是怎么来的

**Comment by Tsuk1ko** [comment]
我是抄的其他类似项目的，这个值可以从签到页面 js 逆推得出，不过由于是压缩的 js 所以实际要找出相关逻辑也不是很容易

**Comment by sunyajie0829** [comment]
> 我是抄的其他类似项目的，这个值可以从签到页面 js 逆推得出，不过由于是压缩的 js 所以实际要找出相关逻辑也不是很容易

嗯，看了几个项目，这个值确实是固定的。感谢分享👍
