### ISSUE TITLE
使用node 部署，出现下面问题

### ISSUE THREAD

**Issue by Li-best** [Tsuk1ko/genshin-mys-checkin#7]
抓包应该是没问题的，

提示以下

读取 cookie 缓存
Cookie 有效，无需重新登陆
开始使用国际版 API 签到
签到失败: {}
「1天签到礼包」领取失败：7月21日0:00开始连续签到1天才能领取礼包，快去签到吧！

**Comment by Tsuk1ko** [comment]
是安卓还是iOS

**Comment by Li-best** [comment]
安卓客户端，下载微博国际版，
抓到了这几个参数填入
"alc": "",
      "aid": "",
      "gsid": "",
      "s": "

**Comment by Tsuk1ko** [comment]
试一下这个分支，配置里面多加个 `"from": "xxx"`，也是抓包拿

https://github.com/Tsuk1ko/genshin-mys-checkin/tree/test/from

**Comment by Li-best** [comment]
WB[0]
登录中
登录成功
保存 cookie 至缓存
开始使用国际版 API 签到
签到成功
「3天签到礼包」领取失败：7月21日0:00后连续签到3天以上才能领取礼包，快去签到吧！

**Comment by Tsuk1ko** [comment]
那行了，看起来 from 参数安卓还是得要，我稍后更新 master

**Comment by Li-best** [comment]
但是也有个小问题，为什么礼包领取失败了呢

**Comment by Tsuk1ko** [comment]
你那天已经把第二天的礼包领了，第三天的要下一天签到了才能领
