### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by xANoyU** [Tsuk1ko/genshin-mys-checkin#8]
`签到请求失败，进行重试 Error: Request failed with status code 429`
添加了很多账号，是因为请求频繁吗，或者可以设置个完成签到后等待3s进行下一个账号签到

**Comment by Tsuk1ko** [comment]
是米游社签到出现这个么

**Comment by xANoyU** [comment]
> 是米游社签到出现这个么

是的
